apiVersion: v1
kind: Secret
metadata:
  name: docker-credentials
  namespace: test
data:
  # echo -n "docker-registry.docker-registry.svc.cluster.local:5000" | base64
  .dockerconfigjson: ewogICJhdXRocyI6IHsKICAgICJkb2NrZXItcmVnaXN0cnkuZG9ja2VyLXJlZ2lzdHJ5LnN2Yy5jbHVzdGVyLmxvY2FsOjUwMDAiOiB7CiAgICAgICJ1c2VybmFtZSI6InRlc3R1c2VyIiwKICAgICAgInBhc3N3b3JkIjoidGVzdHBhc3N3b3JkIiwKICAgICAgImVtYWlsIjogIiIsCiAgICAgICJhdXRoIjogImRHVnpkSFZ6WlhJNmRHVnpkSEJoYzNOM2IzSmsiCiAgICB9CiAgfSwKICAiaW5zZWN1cmUtcmVnaXN0cmllcyI6IFsKICAgICJkb2NrZXItcmVnaXN0cnkuZG9ja2VyLXJlZ2lzdHJ5LnN2Yy5jbHVzdGVyLmxvY2FsOjUwMDAiCiAgXQp9
type: kubernetes.io/dockerconfigjson
# https://kubernetes.io/docs/concepts/containers/images/#specifying-imagepullsecrets-on-a-pod
# https://kubernetes.io/docs/tasks/configure-pod-container/pull-image-private-registry/