apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: statestore
  namespace: test
spec:
  type: state.redis
  metadata:
  - name: redisHost
    value: redis-master.redis.svc.cluster.local:6379
  - name: redisPassword
    secretKeyRef:
      name: redis-credentials
      key: password
  - name: actorStateStore
    value: "true"
  version: v1
